### PR TITLE
Fix scroll in some Android devices

### PR DESCRIPTION
**Pull request by davidbayo10**
Scrollify was not working correctly in some Android Devices. So, I bring you the solution.

### CODE REVIEW

**Comment by kitsunde** [comment]
Ah I didn't spot this, so I did the same thing although mine detects passive support, keeps existing options and makes sure the removeEventListener still works.

https://github.com/lukehaas/Scrollify/pull/245

**Comment by davidbayo10** [comment]
But that PR didn't build minified version. You should accept someone else, and close other.

**Comment by kitsunde** [comment]
Building a minified version in pull requests isn't very useful since every pull request would be a merge conflict.

**Comment by davidbayo10** [comment]
then Will you close this PR?

**Comment by kitsunde** [comment]
It's not my project, I'm just some dude that sent a different PR.

**Comment by davidbayo10** [comment]
ok

**Comment by lukehaas** [comment]
Closing as it looks like these changes have made their way in via a different PR.

**Pull request closed without merging**
